# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - "test"

.test:
  script:
    - id
    - apk add build-base sudo git
    - python -V
    - pip install -r test-requirements.txt codecov
    - pytest --cov -m "ci and not slow"
    - pylint -E lib/*py
    - codecov

test-2.7:
  extends: ".test"
  stage: "test"
  image: "python:2.7.17-alpine3.11"

test-3.6:
  extends: ".test"
  stage: "test"
  image: "python:3.6.10-alpine3.11"
