sudo: true
language: python
branches:
    only:
      - master
matrix:
  include:
  - os: linux
    python: '2.6'
  - os: linux
    python: '3.6'
install:
  - pip install -r test-requirements.txt
script:
  - pylint -E lib/*py
  - coverage run --source=lib/ -m nose --where lib/tests
after_success:
  - pip install coveralls==1.0
  - coveralls
